### ISSUE TITLE
ENERGY_KILO_WATT_HOUR will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead

### ISSUE THREAD

**Issue by nohn** [JaccoR/hass-entso-e#146]

**Comment by MBungalski** [comment]
Looks like it is already fixed in commit c286eee98a3df7c262821e2d089ff3945701a987

**Comment by olafz** [comment]
> Looks like it is already fixed in commit [c286eee](https://github.com/JaccoR/hass-entso-e/commit/c286eee98a3df7c262821e2d089ff3945701a987)

There doesn't seem to be [a version released](https://github.com/JaccoR/hass-entso-e/releases) since this commit. As a consequence, you still get the same error with the most recent Home Assistant (`2024.4.4`) and the most recent ENTSO-e addon (version `v0.3.0`).

**Comment by aodtcr** [comment]
Still an issue, as there is no version update.

```
Logger: homeassistant.const
Source: helpers/deprecation.py:206
First occurred: 10:40:11 (1 occurrences)
Last logged: 10:40:11

ENERGY_KILO_WATT_HOUR was used from entsoe, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please report it to the author of the 'entsoe' custom integration
```

**Comment by Roeland54** [comment]
v0.4.0 is released this version contains fixes that solve a lot of warnings and known issues. This issue is probably also solved.
Please update to the latest version.
Closing this issue for now. If you still have issue please feel free to open a new issue.
