### ISSUE TITLE
Wrong date/time in average_electricity_price_today

### ISSUE THREAD

**Issue by VictorvandenHoven** [JaccoR/hass-entso-e#171]
Unfortunately, the old closed issue #144  about the dates of the attributes of the entity 'sensor.average_electricity_price_today' that remain fixed and don't change anymore, is still there.
The issue happens every now and then, also in version 0.4.2.

**Comment by SjaakPeer** [comment]
Yes, I have the same issue again as well, since update to 0.4.2: Even worse: The previously proposed fix in issue #158 does not longer work: A full (manual) cleanup the core.restore_state file does somehow does not fix the bug, as old data keeps on re-appearing after a "ha core start". Pls fix!

**Comment by maartenlandman89** [comment]
I have the same. The data of 1 September is tomorrow and 2 September is today. 
Even when I make a new setup, it’s still the same.

**Comment by Roeland54** [comment]
Multiple things are at play here. Currently the entso-e platform is not responding with the prices of tomorrow. That is something we will not be able to solve. 

But there is also a bug in the parsing of an incomplete response of the API where dates gets mixed-up. I'll look into fixing that a.s.a.p. 

Thanks for reporting.

**Comment by firefixmaarten** [comment]
Nice to have someone on this project, highly appreciated! @Roeland54

**Comment by SjaakPeer** [comment]
> Multiple things are at play here. Currently the entso-e platform is not responding with the prices of tomorrow. That is something we will not be able to solve.
> 
> But there is also a bug in the parsing of an incomplete response of the API where dates gets mixed-up. I'll look into fixing that a.s.a.p.
> 
> Thanks for reporting.

Update: Now (september 3rd) my issues appear to have resolved itself as I get updated data in the right format again. You may have been correct on the multiple issues at play here.

**Comment by richardstroobach** [comment]
Here it is also fixed now, after a restart of home assistant.

**Comment by Roeland54** [comment]
@richardstroobach can you look in de logs from before your restart? They should be in the "home-assistant.log.1" file. 
And search for entsoe. Do you find logs in de last 2 hours? can you paste them here?

**Comment by richardstroobach** [comment]
**The last entso-e logs are from these:**

0.25833, Timestamp('2024-09-02 16:00:00+0200', tz='Europe/Amsterdam'): 0.26558, Timestamp('2024-09-02 17:00:00+0200', tz='Europe/Amsterdam'): 0.28823, Timestamp('2024-09-02 18:00:00+0200', tz='Europe/Amsterdam'): 0.32491, Timestamp('2024-09-02 19:00:00+0200', tz='Europe/Amsterdam'): 0.46084, Timestamp('2024-09-02 20:00:00+0200', tz='Europe/Amsterdam'): 0.40634, Timestamp('2024-09-02 21:00:00+0200', tz='Europe/Amsterdam'): 0.31298, Timestamp('2024-09-02 22:00:00+0200', tz='Europe/Amsterdam'): 0.29045, Timestamp('2024-09-02 23:00:00+0200', tz='Europe/Amsterdam'): 0.27749}, 'dataTomorrow': {}}

**Before the restart I see alot of these errors:**
2024-09-03 00:00:00.568 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.entsoeplatform_average_electricity_price_today fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 942, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1300, in async_device_update
    await self.async_update()
  File "/config/custom_components/entsoe/sensor.py", line 210, in async_update
    self._attr_extra_state_attributes = {x: self.coordinator.processed_data()[x] for x in self.coordinator.processed_data() if x not in invalid_keys and x not in existing_entities}
                                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/entsoe/coordinator.py", line 167, in processed_data
    "min_price": self.get_min_price(filtered_hourprices),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/entsoe/coordinator.py", line 209, in get_min_price
    return min(hourprices.values())
           ^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: min() iterable argument is empty

**Comment by Roeland54** [comment]
Ok that helps. Should be fixed in the next release.

**Comment by Roeland54** [comment]
The beta version of [v0.5.0-beta1](https://github.com/JaccoR/hass-entso-e/releases/tag/v0.5.0-beta1) does contain a lot of changes to improve reliability. 
Can you test and provide feedback?

**Comment by max19751** [comment]
Also the beta v0.5.0-beta3 still shows the average electricity prices for **tomorrow** with dates of _yesterday_ and _today_.

**Comment by Roeland54** [comment]
> Also the beta v0.5.0-beta3 still shows the average electricity prices for **tomorrow** with dates of _yesterday_ and _today_.

If you are using the default calculation method (publish) and the prices of tomorrow are not know yet this is expected behavior.  Please open a new issue if you think there is something wrong.

**Comment by max19751** [comment]
> > Also the beta v0.5.0-beta3 still shows the average electricity prices for **tomorrow** with dates of _yesterday_ and _today_.
> 
> If you are using the default calculation method (publish) and the prices of tomorrow are not know yet this is expected behavior. Please open a new issue if you think there is something wrong.

Understood, the solves the problem. Many thanks for the swift reaction

**Comment by Roeland54** [comment]
v0.5.0 is released. The discussed issues should be solved. Please feel free to open a new issue if you feel this is needed.
