### ISSUE TITLE
Prices are not mapped correctly because of entsoe api changes

### ISSUE THREAD

**Issue by Roeland54** [JaccoR/hass-entso-e#190]
The api response of the entsoe api has changed format and will not contain the price of a specific hour (position) if the price is the same as the previous hour. So based on the resolution of the dataset the empty spots should be filled with correct price.

![image](https://github.com/user-attachments/assets/9d5a1158-9e82-44d3-b1c8-ead3803c9d45)

Besides that change I have observed that the price for tomorrow in belgium is not returned in the usual 60min resolution but in the 15min resolution instead. 

![image](https://github.com/user-attachments/assets/fe52a589-72be-47f4-a407-a3c1ac533341)

**Comment by RudyDevroey** [comment]
Belgian here, since midnight the sensor is unavailable.

**Comment by XalaTheShepard** [comment]
Last update fixed it for Belgian sensors, but indeed as of midnight unavailable again.

**Comment by Roeland54** [comment]
So looking at the response of the api now. It looks like the prices for tomorrow are back to the expected 60min resolution. This could have been a one of mistake. I think this will fix itself tomorrow.

**Comment by Pluimvee** [comment]
Resolved the missing hours issue in a branch

**Comment by XalaTheShepard** [comment]
Dear all, the issue is still present and has not resolved itself as was expected. For the Belgian sensors the data is still not pushed through. If I can help you providing more information, please let me know. Kind regards, Robin

**Comment by Roeland54** [comment]
As the Belgian data issue is separate from the change of the curvetype I have create a separate issue to followup: #195

**Comment by Roeland54** [comment]
There is a beta version you can install from hacs: [v0.6.3-beta1](https://github.com/JaccoR/hass-entso-e/releases/tag/v0.6.3-beta1)

**Comment by firefixmaarten** [comment]
`Logger: custom_components.entsoe.sensor
Bron: custom_components/entsoe/sensor.py:249
integratie: ENTSO-e Transparency Platform ([documentatie](https://github.com/JaccoR/hass-entso-e), [problemen](https://github.com/JaccoR/hass-entso-e/issues))
Eerst voorgekomen: 19:27:18 (18 gebeurtenissen)
Laatst gelogd: 19:28:13

    Unable to update entity 'entsoe.belgium2_Average electricity price': No valid data for today available.
    Unable to update entity 'entsoe.belgium2_Current percentage of highest electricity price': No valid data for today available.
    Unable to update entity 'entsoe.belgium2_Current percentage in electricity price range': No valid data for today available.
    Unable to update entity 'entsoe.belgium2_Time of highest price': No valid data for today available.
    Unable to update entity 'entsoe.belgium2_Time of lowest price': No valid data for today available.`
    
    Still seems to be happening
